- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: platypodes
  tasks:
  - name: Install pip, MySQL
    apt:
      name:
        - mysql-server
        - python3-mysqldb
      update_cache: yes
      cache_valid_time: 3600
    become: yes
  - name: Start the MySQL service
    become: yes
    service:
      name: mysql
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    become: yes
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
# Todo: Grant normal user privs https://dba.stackexchange.com/questions/49803/what-are-reasonable-privileges-to-grant-typical-users
  - name: Copy my.cnf
    copy:
      src: my.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld_custom.cnf
    become: y
  - name: Retart the MySQL service
    become: yes
    service:
      name: mysql
      state: restarted
      enabled: true
  - name: Enable firewall
    ufw:
      state: enabled
      policy: deny
      rule: allow
      port: 22
    become: y
  - name: Open ports
    ufw:
      rule: allow
      port: '{{ item }}'
    with_items:
      - 10000
      - 3306
      - 80
      - 443
    become: y
